---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfotest
  namespace: team-b
  labels:
    app: podinfotest
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.init: regex:^3.10.*
    flux.weave.works/tag.podinfod: semver:~2.1
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: podinfotest
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: podinfotest
    spec:
      initContainers:
      - name: init
        image: alpine:3.10.1
        command:
        - sleep
        - "1"
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
